# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(262, 93)
        self.centralwidget = QtWidgets.QWidget(parent=Login)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.line_usuario = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_usuario.setObjectName("line_usuario")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_usuario)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.line_senha = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_senha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_senha.setObjectName("line_senha")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_senha)
        self.botao_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botao_login.setObjectName("botao_login")
        self.botao_login.clicked.connect(self.login)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.botao_login)
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Entrada do Sistema"))
        self.label.setText(_translate("Login", "Usuario:"))
        self.label_2.setText(_translate("Login", "Senha:"))
        self.botao_login.setText(_translate("Login", "LOGIN"))
    
    def login(self):
        usuario = self.line_usuario.text()
        senha   = self.line_senha.text()
        
        if usuario == "admin" and senha == "nimda":
            from cadaluno import Ui_CadAluno
            self.tela = QtWidgets.QMainWindow()
            self.cad  = Ui_CadAluno()
            self.cad.setupUi(self.tela)
            self.tela.show()
            Login.close()
        
        else:
            from PyQt6.QtWidgets import QMessageBox
            msg = QMessageBox()
            msg.setWindowTitle("Aviso")
            msg.setText("Acesso negado.")
            msg.exec()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec())
